// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX_BL0-IjbWyZCNH9H9UA3O9QOtFN5F88',
    appId: '1:108562577334:web:bda71dec561134a326b317',
    messagingSenderId: '108562577334',
    projectId: 'attendance-app-eac03',
    authDomain: 'attendance-app-eac03.firebaseapp.com',
    storageBucket: 'attendance-app-eac03.firebasestorage.app',
    measurementId: 'G-J7Z24YE0T3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfvCzRKA757zXFD8FA-FGbHpjfF0575P0',
    appId: '1:108562577334:android:d9e0718e0c6587e126b317',
    messagingSenderId: '108562577334',
    projectId: 'attendance-app-eac03',
    storageBucket: 'attendance-app-eac03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCruzhtBEuGHbYf9slhO9XfIeC1d-_R9Dw',
    appId: '1:108562577334:ios:87eae6522721d58026b317',
    messagingSenderId: '108562577334',
    projectId: 'attendance-app-eac03',
    storageBucket: 'attendance-app-eac03.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCruzhtBEuGHbYf9slhO9XfIeC1d-_R9Dw',
    appId: '1:108562577334:ios:87eae6522721d58026b317',
    messagingSenderId: '108562577334',
    projectId: 'attendance-app-eac03',
    storageBucket: 'attendance-app-eac03.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX_BL0-IjbWyZCNH9H9UA3O9QOtFN5F88',
    appId: '1:108562577334:web:7d767432c89de4df26b317',
    messagingSenderId: '108562577334',
    projectId: 'attendance-app-eac03',
    authDomain: 'attendance-app-eac03.firebaseapp.com',
    storageBucket: 'attendance-app-eac03.firebasestorage.app',
    measurementId: 'G-DE42G49784',
  );
}
